"""followers

Revision ID: 3bf8408cfc02
Revises: fc471305141c
Create Date: 2020-01-01 19:35:16.964913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf8408cfc02'
down_revision = 'fc471305141c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('follows_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['follows_id'], ['id'])
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    op.drop_column('followers', 'follows_id')
    # ### end Alembic commands ###
